# Define Cloud Build configuration with unique variables

steps:
- name: 'gcr.io/hugo-build'  # Use the Hugo builder
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-hugo-site:latest', '.']
  cacheFrom: ['gcr.io/$PROJECT_ID/my-hugo-site:latest']

- name: 'gcr.io/cloud-builders/docker'  # Use the Docker builder
  args: ['push', 'gcr.io/$PROJECT_ID/my-hugo-site:latest']

- name: 'gcr.io/cloud-builders/gcloud'  # Use the gcloud builder
  args: 
    - 'run'
    - 'deploy'
    - '$_SERVICE_NAME'  # Use a unique variable for the service name
    - '--image'
    - 'gcr.io/$PROJECT_ID/my-hugo-site:latest'
    - '--region'
    - '$_REGION'  # Use a unique variable for the region
    - '--allow-unauthenticated'
  entrypoint: 'bash'
  script: |
    set -e
    gcloud run deploy $_SERVICE_NAME \
      --image $_IMAGE_NAME \
      --region $_REGION \
      --allow-unauthenticated \
      --platform managed \
      --port 8080

# Define unique variables with clear names
substitutions:
  _SERVICE_NAME: my-hugo-site  # Replace with your service name
  _REGION: asia-south2  # Replace with your desired region
  _IMAGE_NAME: gcr.io/$PROJECT_ID/my-hugo-site:latest